config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-celadon-harrier.sh
        container: qc.acc_fuzzy-amethyst-otter
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cinnamon-avocet.sh
        container: qc.doc_woolly-firebrick-frise
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-smalt-baboon.sh
        container: qc.doc_gloppy-periwinkle-magpie
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-indigo-caracal.sh
        container: qc.doc_silly-turquoise-meerkat
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-platinum-gharial.sh
        container: qc.lic_wiggy-chestnut-fish
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-auburn-vole.sh
        container: qc.met_seedy-puce-centipede
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-pear-pinscher.sh
        container: qc.sec_sloppy-purple-fish
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cornflower-mule.sh
        container: qc.sec_tasty-ecru-squid
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-beige-gopher.sh
        container: qc.sty_skinny-olivine-pinscher
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-fuchsia-blue.sh
        container: qc.sty_scanty-peach-turtle
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-platinum-magpie.sh
        container: qc.sty_scummy-lilac-hornet
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-corn-swan.sh
        container: qc.sty_sloppy-persimmon-panda
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-eleuth.sh
        container: qc.ver_squirrely-violet-wasp
timeout: 5400
