config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.3.2
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-platinum-mouse.sh
        container: qc.acc_goopy-harlequin-rabbit
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-teal-meerkat.sh
        container: qc.doc_skinny-orchid-impala
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-amber-otter.sh
        container: qc.doc_greasy-chestnut-fly
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-burgundy-gharial.sh
        container: qc.doc_pretty-sangria-barracuda
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-rose-bombay.sh
        container: qc.lic_dorky-vermilion-reindeer
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-aquamarine-flounder.sh
        container: qc.met_crappy-salmon-whale
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-smalt-crane.sh
        container: qc.sec_crappy-bistre-ladybird
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-periwinkle-lynx.sh
        container: qc.sec_leaky-pumpkin-salamander
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-beige-walrus.sh
        container: qc.sty_fuzzy-flax-setter
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-chestnut-turkey.sh
        container: qc.sty_baggy-azure-collie
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-jade-cheetah.sh
        container: qc.sty_clammy-peach-raccoon
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-purple-alligator.sh
        container: qc.sty_pretty-periwinkle-goose
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-apricot-panda.sh
        container: qc.sty_blurry-cardinal-greyhound
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-flax-lemming.sh
        container: qc.uni_homely-denim-koala
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cream-rat.sh
        container: qc.ver_homely-ecru-cat
timeout: 5400
