config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-lavender-tarsier.sh
        container: qc.acc_lanky-saffron-barnacle
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-eggplant-earwig.sh
        container: qc.doc_ugly-taupe-fly
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-orange-mau.sh
        container: qc.doc_foggy-gold-ant
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-wheat-deer.sh
        container: qc.doc_shaky-dandelion-ibis
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-brown-chinook.sh
        container: qc.lic_wheezy-cerulean-saola
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-jade-orangutan.sh
        container: qc.met_gimpy-amaranth-goat
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cream-lynx.sh
        container: qc.sec_shabby-sapphire-cassowary
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cornflower-rhinoceros.sh
        container: qc.sec_geeky-apricot-clam
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-razzmatazz-dogfish.sh
        container: qc.sty_tacky-wisteria-gibbon
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-denim-fowl.sh
        container: qc.sty_sickly-violet-collie
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-buff-skunk.sh
        container: qc.sty_queasy-black-gharial
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-apricot-octopus.sh
        container: qc.sty_stealthy-orange-wasp
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-chestnut-heron.sh
        container: qc.ver_whiny-tomato-leopard
timeout: 5400
