config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cardinal-monkey.sh
        container: qc.acc_cranky-firebrick-chow
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-burgundy-swan.sh
        container: qc.doc_thirsty-cream-clam
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-grey-hedgehog.sh
        container: qc.doc_crabby-cream-deer
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-olivine-dugong.sh
        container: qc.doc_squirrely-khaki-wallaby
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-myrtle-fossa.sh
        container: qc.lic_hazy-ruby-pig
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-scarlet-dragonfly.sh
        container: qc.met_wheezy-magenta-fish
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-silver-budgerigar.sh
        container: qc.sec_chummy-chestnut-coyote
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-zucchini-audemer.sh
        container: qc.sec_sunny-ruby-stingray
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-puce-lobster.sh
        container: qc.sty_snippy-brown-cuscus
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-olive-rattlesnake.sh
        container: qc.sty_stuffy-blue-dachshund
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-beige-worm.sh
        container: qc.sty_lousy-cerise-monkey
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-ivory-shrew.sh
        container: qc.sty_chewy-sangria-devil
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-indigo-frise.sh
        container: qc.ver_zippy-peach-mammoth
timeout: 5400
