config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.3.2-beta
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-chartreuse-manatee.sh
        container: qc.acc_seedy-platinum-dragonfly
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-azure-chinchilla.sh
        container: qc.doc_sickly-ruby-chipmunk
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-periwinkle-rattlesnake.sh
        container: qc.doc_thirsty-crimson-dalmatian
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-peach-woodlouse.sh
        container: qc.doc_gimpy-platinum-sheep
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-buff-pinscher.sh
        container: qc.lic_shaggy-asparagus-starfish
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-wheat-otter.sh
        container: qc.met_pokey-coral-kudu
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-khaki-bear.sh
        container: qc.sec_scaly-yellow-whale
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-malachite-uguisu.sh
        container: qc.sec_wiggy-grey-seal
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-violet-dogfish.sh
        container: qc.sty_blurry-ivory-uakari
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-rose-ibis.sh
        container: qc.sty_nippy-persimmon-eel
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-yellow-mole.sh
        container: qc.sty_lanky-cinnabar-ostrich
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-chartreuse-catfish.sh
        container: qc.sty_pokey-peach-akbash
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-olivine-tarantula.sh
        container: qc.sty_gloppy-cerulean-squirt
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cyan-seal.sh
        container: qc.uni_nerdy-scarlet-sponge
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-chocolate-fossa.sh
        container: qc.ver_pasty-chartreuse-chin
timeout: 5400
