config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cerulean-monster.sh
        container: qc.acc_squirrely-rust-barracuda
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-olivine-foxhound.sh
        container: qc.doc_woolly-copper-forest
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-dandelion-opossum.sh
        container: qc.doc_jumpy-razzmatazz-tzu
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lilac-wolf.sh
        container: qc.doc_gloppy-cerulean-badger
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cinnamon-vulture.sh
        container: qc.lic_clammy-harlequin-malamute
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-fuchsia-argentino.sh
        container: qc.met_pasty-xanthic-wolf
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-malachite-robin.sh
        container: qc.sec_sunny-bronze-macaw
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-red-terrier.sh
        container: qc.sec_squirrely-taupe-bee
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-orange-gharial.sh
        container: qc.sty_lumpy-corn-dogfish
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-bronze-okapi.sh
        container: qc.sty_shabby-corn-coyote
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ecru-bobcat.sh
        container: qc.sty_sunny-auburn-grasshopper
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-green-buffalo.sh
        container: qc.sty_pasty-alizarin-fly
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-zucchini-forest.sh
        container: qc.sty_lovely-black-armadillo
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-emerald-stingray.sh
        container: qc.uni_woozy-emerald-wombat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cyan-molly.sh
        container: qc.ver_gimpy-emerald-giraffe
timeout: 5400
