config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-thistle-paradise.sh
        container: qc.acc_leaky-dandelion-mule
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-jade-pinscher.sh
        container: qc.doc_gamy-silver-lion
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-periwinkle-crab.sh
        container: qc.doc_cheeky-rose-mongoose
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-mustard-ibis.sh
        container: qc.doc_lovely-rust-gorilla
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chocolate-stingray.sh
        container: qc.lic_gummy-platinum-numbat
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-alizarin-lobster.sh
        container: qc.met_frumpy-red-spaniel
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chocolate-mole.sh
        container: qc.sec_sunny-olivine-spitz
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.messy-sapphire-stingray.sh
        container: qc.sec_ready-chartreuse-cheetah
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cerise-rattlesnake.sh
        container: qc.sty_tacky-burgundy-lobster
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-amethyst-mist.sh
        container: qc.sty_sleepy-teal-mau
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sepia-zebra.sh
        container: qc.sty_baggy-salmon-moth
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ruby-bloodhound.sh
        container: qc.sty_cranky-auburn-mandrill
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lilac-panda.sh
        container: qc.ver_randy-bronze-kingfisher
timeout: 5400
