config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: sqa
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-smalt-falcon.sh
        container: qc.acc_scanty-razzmatazz-ladybird
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-peach-neanderthal.sh
        container: qc.doc_muzzy-malachite-birman
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-russet-sponge.sh
        container: qc.doc_baggy-crimson-snake
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-teal-zebu.sh
        container: qc.doc_grumpy-gold-binturong
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-mustard-mayfly.sh
        container: qc.lic_snazzy-charcoal-ocelot
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-asparagus-kiwi.sh
        container: qc.met_boozy-silver-mayfly
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-emerald-chamois.sh
        container: qc.sec_silly-jade-pinscher
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-linen-elephant.sh
        container: qc.sec_bumpy-rust-dhole
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-maroon-echidna.sh
        container: qc.sty_grumpy-sepia-setter
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cinnabar-vole.sh
        container: qc.sty_nippy-cardinal-dog
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-orange-chinook.sh
        container: qc.sty_dorky-russet-vulture
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ochre-lynx.sh
        container: qc.sty_jumpy-red-bloodhound
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-yellow-iguana.sh
        container: qc.sty_geeky-cinnabar-rattlesnake
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-chartreuse-emu.sh
        container: qc.uni_hilly-lemon-abyssinian
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-magenta-owl.sh
        container: qc.ver_nippy-xanthic-fish
timeout: 5400
