config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.3.2
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-persimmon-quokka.sh
        container: qc.acc_woozy-wisteria-slug
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chartreuse-burmese.sh
        container: qc.doc_woolly-denim-tiger
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-pear-elephant.sh
        container: qc.doc_sloppy-thistle-urchin
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-azure-balinese.sh
        container: qc.doc_jumpy-purple-newt
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ecru-millipede.sh
        container: qc.lic_geeky-asparagus-mole
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-teal-rabbit.sh
        container: qc.met_cozy-corn-bullfrog
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-mauve-slug.sh
        container: qc.sec_greasy-plum-russel
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-violet-dugong.sh
        container: qc.sec_zippy-firebrick-mongrel
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-thistle-fly.sh
        container: qc.sty_shabby-denim-forest
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-aquamarine-sparrow.sh
        container: qc.sty_paltry-rust-oyster
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-mauve-hummingbird.sh
        container: qc.sty_fuzzy-fuchsia-avocet
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sepia-maltese.sh
        container: qc.sty_snippy-pear-eagle
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-eggplant-buffalo.sh
        container: qc.sty_sickly-azure-shark
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ecru-bordeaux.sh
        container: qc.uni_craggy-tan-bonobo
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-heliotrope-quetzal.sh
        container: qc.ver_craggy-tan-clam
timeout: 5400
