config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chartreuse-crane.sh
        container: qc.acc_flabby-auburn-swan
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-aquamarine-woodlouse.sh
        container: qc.doc_hazy-rose-lion
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-yellow-havanese.sh
        container: qc.doc_silly-goldenrod-lynx
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-periwinkle-tang.sh
        container: qc.doc_shabby-crimson-badger
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnabar-dodo.sh
        container: qc.lic_shaky-charcoal-grasshopper
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-orchid-otter.sh
        container: qc.met_jumpy-ultramarine-discus
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-malachite-terrier.sh
        container: qc.sec_fuzzy-silver-bloodhound
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-vermilion-dog.sh
        container: qc.sec_snazzy-persimmon-gorilla
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-alizarin-robin.sh
        container: qc.sty_slimy-turquoise-frog
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-carmine-russel.sh
        container: qc.sty_baggy-celadon-impala
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-corn-moose.sh
        container: qc.sty_wimpy-champagne-macaw
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-violet-oriole.sh
        container: qc.sty_wheezy-green-okapi
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-black-cichlid.sh
        container: qc.ver_boozy-rose-rattlesnake
timeout: 5400
