config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.3.2
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-carmine-cattle.sh
        container: qc.acc_crabby-eggplant-gibbon
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-orange-mist.sh
        container: qc.doc_droopy-smalt-skunk
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-purple-pinscher.sh
        container: qc.doc_snappy-pear-dalmatian
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-yellow-buzzard.sh
        container: qc.doc_gimpy-violet-markhor
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-burgundy-dog.sh
        container: qc.lic_chummy-tangerine-fish
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-thistle-wallaby.sh
        container: qc.met_gloppy-khaki-meerkat
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-smalt-zonkey.sh
        container: qc.sec_sloppy-violet-dolphin
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-seashell-squirrel.sh
        container: qc.sec_geeky-ochre-affenpinscher
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cerise-echidna.sh
        container: qc.sty_flaky-khaki-dunker
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-teal-zebu.sh
        container: qc.sty_randy-azure-markhor
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-turquoise-manatee.sh
        container: qc.sty_muzzy-maroon-yak
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amber-crane.sh
        container: qc.sty_pasty-taupe-ant
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-zonkey.sh
        container: qc.sty_thirsty-cerise-lemur
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-violet-duck.sh
        container: qc.uni_gummy-puce-cockroach
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-platinum-boar.sh
        container: qc.ver_pasty-smalt-tuatara
timeout: 5400
