config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-black-booby.sh
        container: qc.acc_snazzy-white-snake
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-maroon-binturong.sh
        container: qc.doc_chewy-denim-kangaroo
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-scarlet-toad.sh
        container: qc.doc_flaky-corn-ocelot
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-smalt-worm.sh
        container: qc.doc_sloppy-yellow-catfish
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-orchid-albatross.sh
        container: qc.lic_lumpy-seashell-armadillo
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-wheat-robin.sh
        container: qc.met_cloudy-coral-stoat
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-firebrick-hyena.sh
        container: qc.sec_freaky-mauve-dollar
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-thistle-baboon.sh
        container: qc.sec_cloudy-wheat-numbat
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-russet-duck.sh
        container: qc.sty_gamy-xanthic-beagle
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-gamboge-forest.sh
        container: qc.sty_silly-teal-kiwi
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ochre-argentino.sh
        container: qc.sty_slimy-cornflower-anteater
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-chocolate-bullfrog.sh
        container: qc.sty_silly-magnolia-opossum
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-scarlet-buzzard.sh
        container: qc.ver_slaphappy-lilac-cockroach
timeout: 5400
