config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.3.1
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-tomato-mole.sh
        container: qc.acc_snazzy-magenta-impala
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-magnolia-bordeaux.sh
        container: qc.doc_sleazy-heliotrope-hamster
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-emerald-wolverine.sh
        container: qc.doc_baggy-cyan-hummingbird
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-burgundy-gharial.sh
        container: qc.doc_muggy-khaki-lion
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lilac-wrasse.sh
        container: qc.lic_seedy-tomato-cheetah
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-ochre-frog.sh
        container: qc.met_hasty-ivory-fousek
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ecru-tapir.sh
        container: qc.sec_scaly-ivory-caterpillar
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-green-shrew.sh
        container: qc.sec_clammy-charcoal-squirt
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-red-wolf.sh
        container: qc.sty_sunny-grey-ray
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-aquamarine-opossum.sh
        container: qc.sty_dorky-wheat-fox
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amaranth-ladybird.sh
        container: qc.sty_sloppy-carmine-havanese
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lime-rattlesnake.sh
        container: qc.sty_freaky-auburn-bonobo
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-celadon-dane.sh
        container: qc.sty_jumpy-violet-pinscher
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lemon-yak.sh
        container: qc.uni_cheeky-turquoise-macaque
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-heliotrope-wombat.sh
        container: qc.ver_wiggy-pear-grasshopper
timeout: 5400
