config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: sqa
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-beige-chow.sh
        container: qc.acc_lovely-brass-dodo
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-copper-setter.sh
        container: qc.doc_gamy-chocolate-mongoose
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-peach-whippet.sh
        container: qc.doc_pretty-brass-flounder
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-tan-spider.sh
        container: qc.doc_stinky-cream-serval
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-seashell-hare.sh
        container: qc.lic_woolly-razzmatazz-bloodhound
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-orange-cassowary.sh
        container: qc.met_woozy-bistre-frigatebird
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-grey-clam.sh
        container: qc.sec_baggy-periwinkle-havanese
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-eggplant-dhole.sh
        container: qc.sec_boozy-aqua-rattlesnake
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-wheat-oriole.sh
        container: qc.sty_squirrely-orange-bird
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-teal-fly.sh
        container: qc.sty_craggy-zucchini-argentino
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-gold-rat.sh
        container: qc.sty_messy-olivine-tapir
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cerulean-jackal.sh
        container: qc.sty_sickly-eggplant-jackal
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-grey-retriever.sh
        container: qc.sty_wiggy-asparagus-scorpion
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cardinal-chow.sh
        container: qc.uni_lovely-cerise-buffalo
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amber-owl.sh
        container: qc.ver_smelly-black-paradise
timeout: 5400
