config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-lemon-loon.sh
        container: qc.acc_squirrely-magnolia-beetle
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cardinal-rottweiler.sh
        container: qc.doc_fuzzy-mustard-catfish
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-russet-flamingo.sh
        container: qc.doc_bluesy-pink-cuttlefish
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lilac-olm.sh
        container: qc.doc_muzzy-azure-squirrel
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-beige-raccoon.sh
        container: qc.lic_skimpy-firebrick-quetzal
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-emerald-opossum.sh
        container: qc.met_cranky-aqua-salamander
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bistre-baboon.sh
        container: qc.sec_shaky-eggplant-alligator
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-teal-drever.sh
        container: qc.sec_clammy-amaranth-gerbil
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chartreuse-spitz.sh
        container: qc.sty_snazzy-wheat-coati
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-salmon-rhinoceros.sh
        container: qc.sty_cheeky-wisteria-clam
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pink-koala.sh
        container: qc.sty_stealthy-viridian-alligator
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-aquamarine-forest.sh
        container: qc.sty_leaky-rust-indri
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-chocolate-numbat.sh
        container: qc.sty_bluesy-corn-swan
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cinnamon-foxhound.sh
        container: qc.uni_woolly-rose-bracke
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-scarlet-wildebeest.sh
        container: qc.ver_smelly-razzmatazz-toucan
timeout: 5400
