config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-tomato-owl.sh
        container: qc.acc_wheezy-grey-macaw
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-silver-kangaroo.sh
        container: qc.doc_cheeky-tangerine-cockroach
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cobalt-budgerigar.sh
        container: qc.doc_boozy-green-goose
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-malachite-lynx.sh
        container: qc.doc_snoopy-scarlet-guppy
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-khaki-starfish.sh
        container: qc.lic_woolly-blue-orangutan
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-olivine-fowl.sh
        container: qc.met_pretty-aqua-toucan
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-saffron-mastiff.sh
        container: qc.sec_pasty-cobalt-saola
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-asparagus-toad.sh
        container: qc.sec_scummy-teal-loon
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-olive-clam.sh
        container: qc.sty_crappy-purple-bobcat
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-mauve-gorilla.sh
        container: qc.sty_stealthy-carmine-dugong
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cobalt-numbat.sh
        container: qc.sty_sloppy-eggplant-urchin
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-black-ocelot.sh
        container: qc.sty_smelly-ecru-chow
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.beady-xanthic-ibis.sh
        container: qc.sty_frumpy-bronze-gopher
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-aquamarine-schnauzer.sh
        container: qc.uni_snappy-periwinkle-numbat
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lilac-barracuda.sh
        container: qc.ver_snazzy-silver-ant
timeout: 5400
