config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-violet-caterpillar.sh
        container: qc.acc_breezy-cinnamon-bonobo
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-denim-dragon.sh
        container: qc.doc_geeky-purple-chameleon
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amethyst-chipmunk.sh
        container: qc.doc_sunny-peach-gharial
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-white-otter.sh
        container: qc.doc_stuffy-black-oriole
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-olive-chin.sh
        container: qc.lic_dorky-lavender-worm
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-persimmon-moth.sh
        container: qc.met_smelly-pumpkin-lynx
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-plum-termite.sh
        container: qc.sec_gimpy-thistle-squirrel
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-green-pig.sh
        container: qc.sec_silly-ruby-foxhound
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-tan-hamster.sh
        container: qc.sty_flimsy-dandelion-gharial
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-pink-wrasse.sh
        container: qc.sty_chewy-razzmatazz-akita
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-jade-chinook.sh
        container: qc.sty_chummy-seashell-devil
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cinnamon-cockroach.sh
        container: qc.sty_zippy-persimmon-quetzal
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chartreuse-weasel.sh
        container: qc.sty_surly-tomato-oriole
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cornflower-frise.sh
        container: qc.uni_scummy-sangria-chimpanzee
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-charcoal-penguin.sh
        container: qc.ver_nippy-lemon-goose
timeout: 5400
