config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lavender-markhor.sh
        container: qc.acc_smelly-platinum-javanese
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-silver-camel.sh
        container: qc.doc_frumpy-aquamarine-armadillo
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-malachite-panda.sh
        container: qc.doc_snappy-wisteria-koala
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-scarlet-mayfly.sh
        container: qc.lic_snoopy-chocolate-tang
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-chestnut-meerkat.sh
        container: qc.ver_nerdy-mustard-baboon
timeout: 5400
