config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: v3.6.3-beta
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-maroon-dodo.sh
        container: qc.acc_woozy-cinnabar-rabbit
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-vermilion-hare.sh
        container: qc.doc_lousy-indigo-antelope
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-gold-hare.sh
        container: qc.doc_sleepy-cyan-hyrax
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amethyst-bulldog.sh
        container: qc.doc_slimy-periwinkle-zorse
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lavender-frog.sh
        container: qc.lic_stinky-auburn-chihuahua
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-celadon-opossum.sh
        container: qc.met_squeaky-cornflower-monkey
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-champagne-antelope.sh
        container: qc.sec_chewy-firebrick-scorpion
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-xanthic-caiman.sh
        container: qc.sec_sloppy-aquamarine-spaniel
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-orange-zorse.sh
        container: qc.sty_tacky-bistre-binturong
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-magenta-rottweiler.sh
        container: qc.sty_queasy-thistle-dugong
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pear-malamute.sh
        container: qc.sty_lumpy-platinum-pig
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-razzmatazz-seal.sh
        container: qc.sty_bumpy-russet-barracuda
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-mauve-cassowary.sh
        container: qc.sty_baggy-carmine-numbat
  QC.Uni:
    repos:
      github.com/grycap/oscar commands:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sangria-ragdoll.sh
        container: qc.uni_stealthy-scarlet-hamster
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-chocolate-fossa.sh
        container: qc.ver_cranky-sapphire-spitz
timeout: 5400
