config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-pink-alligator.sh
        container: qc.acc_lovely-eggplant-squid
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-russet-nightingale.sh
        container: qc.doc_muzzy-asparagus-catfish
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-gold-duck.sh
        container: qc.doc_sleepy-pear-fousek
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-rust-molly.sh
        container: qc.doc_breezy-yellow-hedgehog
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-eggplant-termite.sh
        container: qc.lic_queasy-amethyst-axolotl
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cornflower-mammoth.sh
        container: qc.met_homely-olivine-mongrel
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-seashell-harrier.sh
        container: qc.sec_trippy-platinum-forest
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cerulean-dragon.sh
        container: qc.sec_chummy-amaranth-husky
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-periwinkle-horse.sh
        container: qc.sty_sunny-purple-skunk
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-gamboge-iguana.sh
        container: qc.sty_shaky-pear-bear
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pear-bird.sh
        container: qc.sty_freaky-emerald-chin
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ruby-numbat.sh
        container: qc.sty_zippy-auburn-fowl
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-khaki-termite.sh
        container: qc.ver_silly-lime-audemer
timeout: 5400
