config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cream-sponge.sh
        container: qc.acc_pasty-firebrick-gibbon
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerulean-buzzard.sh
        container: qc.doc_gimpy-teal-raccoon
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cerulean-mandrill.sh
        container: qc.doc_greasy-white-dhole
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-white-civet.sh
        container: qc.doc_nippy-linen-seal
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-green-balinese.sh
        container: qc.lic_geeky-cream-meerkat
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-yellow-falcon.sh
        container: qc.met_pokey-cream-capybara
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tomato-leopard.sh
        container: qc.sec_snazzy-teal-lynx
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-auburn-buzzard.sh
        container: qc.sec_chummy-brass-molly
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-mustard-grouse.sh
        container: qc.sty_grumpy-olivine-caracal
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cerulean-ray.sh
        container: qc.sty_nippy-lemon-leopard
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-kangaroo.sh
        container: qc.sty_ready-cyan-whippet
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-pink-balinese.sh
        container: qc.sty_hazy-burgundy-mule
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-tan-lemming.sh
        container: qc.sty_muzzy-lemon-kingfisher
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-salmon-numbat.sh
        container: qc.uni_gimpy-champagne-mau
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-rose-reindeer.sh
        container: qc.ver_craggy-indigo-burmese
timeout: 5400
