config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: micafer_dev
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lime-penguin.sh
        container: qc.acc_cranky-maroon-burmese
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-champagne-kudu.sh
        container: qc.doc_seedy-platinum-capuchin
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-tomato-bullfrog.sh
        container: qc.doc_randy-wisteria-tarsier
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amethyst-bee.sh
        container: qc.doc_scaly-amaranth-ladybird
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-beaver.sh
        container: qc.lic_surly-copper-penguin
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-burgundy-flounder.sh
        container: qc.met_squeaky-emerald-shrimp
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-turquoise-walrus.sh
        container: qc.sec_chewy-alizarin-mule
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cornflower-bee.sh
        container: qc.sec_crappy-auburn-wolverine
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-pumpkin-dogfish.sh
        container: qc.sty_lousy-brass-caiman
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-burgundy-frigatebird.sh
        container: qc.sty_foggy-emerald-frise
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-tomato-caterpillar.sh
        container: qc.sty_cozy-tan-foxhound
      github.com/grycap/oscar oclint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cobalt-mule.sh
        container: qc.sty_frumpy-green-crane
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-champagne-moth.sh
        container: qc.sty_breezy-thistle-chow
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-celadon-millipede.sh
        container: qc.uni_woolly-harlequin-wallaby
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-linen-dalmatian.sh
        container: qc.ver_chewy-silver-tiger
timeout: 5400
