config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-goldenrod-caracal.sh
        container: qc.acc_shaggy-ivory-cuscus
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-turquoise-bear.sh
        container: qc.doc_boozy-cinnamon-cichlid
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-harlequin-tortoise.sh
        container: qc.doc_snappy-aqua-bracke
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-magnolia-dollar.sh
        container: qc.doc_slimy-jade-insect
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ecru-labradoodle.sh
        container: qc.lic_tacky-puce-penguin
  QC.Met:
    repos:
      github.com/grycap/oscar validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-orange-affenpinscher.sh
        container: qc.met_messy-charcoal-whippet
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-purple-russel.sh
        container: qc.sec_homely-pear-dachshund
      github.com/grycap/oscar gosec:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-zucchini-spaniel.sh
        container: qc.sec_snoopy-ivory-serval
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-green-grouse.sh
        container: qc.sty_ugly-persimmon-badger
      github.com/grycap/oscar hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cardinal-paradise.sh
        container: qc.sty_squirrely-charcoal-hamster
      github.com/grycap/oscar jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-sapphire-saola.sh
        container: qc.sty_lousy-gold-barnacle
      github.com/grycap/oscar staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.randy-firebrick-baboon.sh
        container: qc.sty_clammy-indigo-fish
  QC.Uni:
    repos:
      github.com/grycap/oscar pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-black-echidna.sh
        container: qc.uni_gamy-cerulean-russel
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-razzmatazz-indri.sh
        container: qc.ver_smelly-mauve-bracke
timeout: 5400
